### ISSUE TITLE
error with tempory fil with pipeline_mapping.py

### ISSUE THREAD

**Issue by csandorfr** [CGATOxford/cgat#103]
Hi,

by running the pipeline_mapping.py with gsnap as mapper, I have the following error:

015-01-18 14:05:56,240 ERROR Experiment.error.1016 0: Task=mapReadsWithGSNAP Error=exceptions.OSError Job=[[./Live-NHDF1-1-R1.fastq.1.gz,gsnap.dir/splicesites.iit]->gsnap.dir/Live-NHDF1-1-R1.gsnap.bam]: ([Errno 2] No such file or directory: '/scratch/ctmpMa1W98')
2015-01-18 14:05:56,241 ERROR Experiment.error.1016 1: Task=mapReadsWithGSNAP Error=exceptions.OSError Job=[[./Live-OX119-1-R1.fastq.1.gz,gsnap.dir/splicesites.iit]->gsnap.dir/Live-OX119-1-R1.gsnap.bam]: ([Errno 2] No such file or directory: '/scratch/ctmpzLx0i4')

In pipeline.ini I configured the following variable like this:

scratchdir for data not to be backed up
scratchdir=/net/isi-scratch/cynthia/tmp

I don't undestand why pipeline_mapping try to find a tempory file in /scratch

Cynthia

**Comment by jethrojohnson** [comment]
This is because the base class in PipelineMapping.py calls Pipeline.getTempDir()

Within Pipeline.py, when no directory  argument is supplied,  getTempDir defaults to HARCODED_PARAMS["shared_tmpdir"], which is set to /ifs/scratch/

Is there a reason to have both scratchdir and shared_tmpdir within PARAMS dict, or would it be okay to combine them to prevent this happening in future?

**Comment by AndreasHeger** [comment]
There is a difference between the two:

1. local scratch:  tmpdir
2. shared scratch: shared_tmpdir

Best

**Comment by csandorfr** [comment]
I modified in:

(1) local pipeline.ini: shared_tmpdir=/net/isi-scratch/cynthia
(2) CGATPipelines/configuration/pipeline.ini shared_tmpdir=/net/isi-scratch/cynthia
(3) I modified in script Pipeline.py in HARCODED_PARAMS 'shared_tmpdir': '/net/isi-scratch/cynthia'

I have still the same error.
