### ISSUE TITLE
How to run DESeq2 with pipeline_rnadiffexpression.py

### ISSUE THREAD

**Issue by csandorfr** [CGATOxford/cgat#138]
Hi,

I would like use DESeq2 instead of DESEq with pipeline_rnadiffexpression.py. I was wondering what is parameter I should change.

Cynthia

**Comment by jethrojohnson** [comment]
Hi Cynthia,

It should be possible to set the methods field in pipeline.ini to 
deseq2.  Currently I would advise running the pipeline only to 
loadDESeq2 (i.e. not to full), because the DESeq2 output has not yet 
been modified to conform to the generic format required for the 
downstream analysis.

Thanks

Jethro



On 02/13/15 14:34, csandorfr wrote:
>
> Hi,
>
> I would like use DESeq2 instead of DESEq with 
> pipeline_rnadiffexpression.py. I was wondering what is parameter I 
> should change.
>
> Cynthia
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CGATOxford/cgat/issues/138>.
>


-- 
Dr Jethro Johnson
CGAT Genomics Training Fellow
MRC Functional Genomics Unit
University of Oxford
+44 1865 282362

**Comment by csandorfr** [comment]
Hi Jethro,

I don't find function loadDESeq2 but only loadDESEq in the pipeline_rnaseqdiffexpression.py. I updated my version of CGAT pipeline:

(cgat-venv)bash-4.1$ git pull
Already up-to-date

Thanks

Cynthia

**Comment by jethrojohnson** [comment]
Hi Cynthia, 

Apologies, my mistake, the function loadDESeq2 is currently on a separate git branch (JJTS-RefactorExpressionAndRunExpression), which hasn't been pushed to origin/master.

The function runDESeq2 should, however, be in your current code, since it has already been merged (9aa405c). You could therefore get the DESeq2 results directly from a flatfile (./deseq2.dir/*.feature_counts.tsv.gz). 

As I mentioned, further changes haven't been pushed to master as I've not yet decided how to reconcile output from DESeq2's multi-factor designs with the standard DE output required by pipeline_rnaseqdiffexpression.py for downstream analysis.

**Comment by csandorfr** [comment]
Hi Jethro,

It worked. 

I was wondering if I want to use covariate as sex and age, how I should add this parameters for runDESeq2

Thanks

Cynthia

**Comment by jethrojohnson** [comment]
Hi Cynthia,

First, you should be able to add additional columns to the design table 
containing factor levels for your covariates.
Second, you should be able to add the model design (using standard R 
syntax) to the deseq2_model field in the pipeline.ini file.
Finally, if you want to report all contrasts, then leave the 
deseq2_contrasts field, blank. Otherwise you have to specify the 
individual contrasts as factor:control:treatment in this field (see the 
help section of runExpression.py for further details).

I hope this works for you!

Thanks

Jethro

On 02/16/15 12:42, csandorfr wrote:
>
> Hi Jethro,
>
> It worked.
>
> I was wondering if I want to use covariate as sex and age, how I 
> should add this parameters for runDESeq2
>
> Thanks
>
> Cynthia
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CGATOxford/cgat/issues/138#issuecomment-74502872>.
>


-- 
Dr Jethro Johnson
CGAT Genomics Training Fellow
MRC Functional Genomics Unit
University of Oxford
+44 1865 282362

**Comment by TomSmithCGAT** [comment]
I assume this can be closed?..

**Comment by csandorfr** [comment]
Yes we can close this issue.

Cynthia
