### ISSUE TITLE
different between feature_counts.dir/genesetexons.feature_counts.tsv.gz and gene_counts.dir/genesetexons.gene_counts.tsv.gz

### ISSUE THREAD

**Issue by csandorfr** [CGATOxford/cgat#141]
Hi,

These two read count file are make when I run pipeline_rnaseqdiffexpression.py loadDESeq

I was wondering what is the different between two file. I know that it is the first that is considered in DESeq analyses.

Thanks

Cynthia

**Comment by jethrojohnson** [comment]
Hi Cynthia,

The difference is in the tool used to create the count tables passed to 
DESeq.

The first file uses feature counts to create the count table, where as 
the second uses the CGAT script gtf2table.
Any differences between these two files should be due to the parameters 
passed to featureCounts, which can be specified in the pipeline.ini file.

If you are interested in how gtf2table is run, then have a look at the 
ruffus task buildGeneLevelRead counts in pipeline_rnaseqdiffexpression.py

Thanks

Jethro


On 02/18/15 10:36, csandorfr wrote:
>
> Hi,
>
> These two read count file are make when I run 
> pipeline_rnaseqdiffexpression.py loadDESeq
>
> I was wondering what is the different between two file. I know that it 
> is the first that is considered in DESeq analyses.
>
> Thanks
>
> Cynthia
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CGATOxford/cgat/issues/141>.
>


-- 
Dr Jethro Johnson
CGAT Genomics Training Fellow
MRC Functional Genomics Unit
University of Oxford
+44 1865 282362
