### ISSUE TITLE
Documentation website

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#146]
Hi Guys,

Many of the tool references on the website are down because of a samtools change (The web pages just give a python error along the lines of 'module' has no attribute Fastafile in csamtools.)

I'm introducing people here to the code collection tomorrow, so it would be good if this worked. 

Ian
---

**Comment by AndreasHeger** [comment]
Sorry, bad timing. On leave until Monday. Make html should do the trick. Best wishes, andreas                                                                                                                                                                                                                                                                           Sent from my BlackBerry 10 smartphone on the EE network.                                                                                                                                                                                                                                         From: Ian SudberySent: Thursday, 19 February 2015 22:33To: CGATOxford/cgatReply To: CGATOxford/cgatSubject: [cgat] Documentation website (#146)Hi Guys,

Many of the tool references on the website are down because of a samtools change (The web pages just give a python error along the lines of 'module' has no attribute Fastafile in csamtools.)

I'm introducing people here to the code collection tomorrow, so it would be good if this worked. 

Ian

—Reply to this email directly or view it on GitHub.

**Comment by AndreasHeger** [comment]
@IanSudbery 

I have rebuilt the documentation and published it.
