### ISSUE TITLE
error: 'AlignedSegment' is not a type identifier

### ISSUE THREAD

**Issue by sjackman** [CGATOxford/cgat#156]
When I `pip install --upgrade cgat`, I get the error message `'AlignedSegment' is not a type identifier`. Here's the [complete gist](https://gist.github.com/sjackman/6f44ff96bf085973bfa4). Mac OS 10.10.1. Python 2.7.9. Dependencies installed using Homebrew.

```
clang -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.10-x86_64-2.7/CGAT/NCL/cnestedlist.o build/temp.macosx-10.10-x86_64-2.7/CGAT/NCL/intervaldb.o -o build/lib.macosx-10.10-x86_64-2.7/CGAT/NCL/cnestedlist.so
    cythoning scripts/_bam2bam.pyx to scripts/_bam2bam.c

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef bint c_remove_mismatches = remove_mismatches
        cdef bint c_remove_unmapped = remove_unmapped

        cdef int * remove_contig_tids
        cdef int nremove_contig_tids = 0
        cdef AlignedSegment read
            ^
    ------------------------------------------------------------

    scripts/_bam2bam.pyx:97:9: 'AlignedSegment' is not a type identifier
```

**Comment by sjackman** [comment]
I see the identical error on Linux (CentOS 5.10).

**Comment by sebastian-luna-valero** [comment]
Dear Shaun,

Could you please make sure that you have the latest version of pysam
installed and try again?

Best regards,
Sebastian


2015-03-10 19:17 GMT+00:00 Shaun Jackman <notifications@github.com>:

**Comment by sjackman** [comment]
I thought that `pip install --upgrade cgat` also upgrades dependencies. I'm confused why it did not. In any case, a `pip install --upgrade pysam` resolved that error. I have a new error now.

```
clang -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.10-x86_64-2.7/CGAT/NCL/cnestedlist.o build/temp.macosx-10.10-x86_64-2.7/CGAT/NCL/intervaldb.o -o build/lib.macosx-10.10-x86_64-2.7/CGAT/NCL/cnestedlist.so
cythoning scripts/_bam2bam.pyx to scripts/_bam2bam.c
Error compiling Cython file:
------------------------------------------------------------
...
        # L = 1 byte (unsigned char)
        def _gen(): return array.array('B')
        index = collections.defaultdict(_gen)
        while ret > 0:
            ret = bam_read1(reference_samfile.fp, b)
                                            ^
------------------------------------------------------------
scripts/_bam2bam.pyx:137:45: Cannot convert Python object to 'BGZF *'
```

**Comment by sebastian-luna-valero** [comment]
Dear Shaun,

That error should have been fixed by updating pysam as well. It seems like
your environment has not been cleaned up.

Have you followed our installation procedure for OS X?
https://www.cgat.org/downloads/public/cgat/documentation/CGATInstallationOSX.html#cgatinstallationosx

If you continue having problems, and you just want to try out our code, may
I suggest that you try our alternative installation methods with
VirtualBox, Vagrant or Docker?
https://www.cgat.org/downloads/public/cgat/documentation/CGATInstallation.html#cgat-code-clean-installation

Best regards,
Sebastian.


2015-03-10 23:15 GMT+00:00 Shaun Jackman <notifications@github.com>:

**Comment by sjackman** [comment]
A few comments on the OS X installation instructions.

`brew install gfortran` should be `brew install gcc` because

```
❯❯❯ brew install gfortran
Error: No available formula for gfortran 
GNU Fortran is now provided as part of GCC, and can be installed with:
  brew install gcc
```

bedtools is in Homebrew. `brew install homebrew/science/bedtools`

Why is this step necessary `pip install -r requires.txt`?
Shouldn't `pip install cgat` handle dependencies?

> Also, bx-python needs to be installed. The current version on pypi is currently out of date

Is this still true?

**Comment by AndreasHeger** [comment]
Apologies, the thread has become quiet. In theory you are right, except for some dependencies such as pysam that need to be present during the first invocation of setup.py in order to obtain
the location of include and library files. In practice a separate step makes sure that all is there.

Another benefit of `pip install -r requires.txt` is that it separates the installation of the dependencies from the installation of our package and thus helps us in debugging.
Some scripts require bx.python, without it it will a bit hit-and-miss.

Best wishes,
Andreas
