### ISSUE TITLE
pysam 0.8.4 not working

### ISSUE THREAD

**Issue by pescobar** [CGATOxford/cgat#250]
Hi 

As defined in the requirements file I installed  pysam-0.8.4
https://github.com/CGATOxford/cgat/blob/master/requires.txt#L19

But then I get this error when trying to compile
```
gcc: error: /scicore/home/zavolan/gypas/soft/cgat-python/lib/python2.7/site-packages/pysam/TabProxies.so: No such file or directory
    error: command 'gcc' failed with exit status 1
```

I found that this problem is because pysam has renamed TabProxies to ctabixproxies in release 0.8.4 so file TabProxies.so is no longer available in pysam-0.8.4. The change is described in the pysam release notes
https://github.com/pysam-developers/pysam/blob/master/doc/release.rst

To workaround this issue I had to install pysam-0.8.3 instead of 0.8.4

**Comment by IanSudbery** [comment]
This suggests to me that the version of CGAT you are using is not fully up
to date. How are you installing CGAT?



*From:* Pablo Escobar Lopez [mailto:notifications@github.com]
*Sent:* 20 February 2016 08:49
*To:* CGATOxford/cgat
*Subject:* [cgat] pysam 0.8.4 not working (#250)



Hi

As defined in the requirements file I installed pysam-0.8.4
https://github.com/CGATOxford/cgat/blob/master/requires.txt#L19

But then I get this error when trying to compile

gcc: error: /scicore/home/zavolan/gypas/soft/cgat-python/lib/python2.7/site-packages/pysam/TabProxies.so:
No such file or directory

    error: command 'gcc' failed with exit status 1

I found that this problem is because pysam has renamed TabProxies to
ctabixproxies in release 0.8.4 so file TabProxies.so is no longer available
in pysam-0.8.4. The change is described in the pysam release notes
https://github.com/pysam-developers/pysam/blob/master/doc/release.rst

To workaround this issue I had to install pysam-0.8.3 instead of 0.8.4

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/cgat/issues/250>.

**Comment by pescobar** [comment]
I installed it doing ```pip install cgat``` inside a python virtual env

I think I am using the latest release 0.2.4

```
(cgat-python)[gypas@login18 ~]$ which cgat
~/soft/cgat-python/bin/cgat
```
```
(cgat-python)[gypas@login18 ~]$ head -3 `which cgat`
#!/scicore/home/zavolan/gypas/soft/cgat-python/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'CGAT==0.2.4','console_scripts','cgat'
__requires__ = 'CGAT==0.2.4'
```

**Comment by IanSudbery** [comment]
Yes, your not the first person to have problems with the pip install and pysam 0.8.4.
There are three options:
1) Unless you need pysam 0.8.4 for anything else, there shouldn't be any problem running pysam 0.8.3

However, if you wish to use pysam 0.8.4, you could either:
2) Install via conda
3) clone the code from Github and use that.

@sebastian-luna-valero Can we make sure the pypy copy of the code is the same as conda?

**Comment by pescobar** [comment]
thanks, I will keep using pysam-0.8.3 in the virtualenv where I installed cgat

I think anyone following this documentation would hit the same problem than me
https://www.cgat.org/downloads/public/cgat/documentation/CGATInstallation.html#manual-installation

**Comment by IanSudbery** [comment]
This issue has been consolidated with several others on issue #252, please see there for further developments.
