### ISSUE TITLE
Tests for commit work fine on my system. Fail on travis

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#98]
Hi Guys,

Tests for 95ad3bdfbffbf86ce953abb6df04905c9fe4c2a2 complete fine on my system, but fail on travis. Any ideas?

**Comment by sebastian-luna-valero** [comment]
Hi Ian,

According to the output here:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/47121310/log.txt

The error is:
from scipy.linalg import calc_lwork
ImportError: cannot import name calc_lwork

I have been looking for help out there, and the problem is being discussed here:
https://github.com/scipy/scipy/pull/3871

Let's keep an eye on this to see what to do. I will update you with the outcome.

Best regards,
Sebastian.

**Comment by IanSudbery** [comment]
Ah. I'm probably not getting the error on my environment because I probably havn't updated SciPy.

**Comment by sebastian-luna-valero** [comment]
Hi all,

While this issue is being solved, I have enforced the installation of SciPy
0.14 with Conda until version 0.15 fixes the problem.

This issue should not be closed until SciPy developers propose a solution
at their end.

Best regards,
Sebastian.


2015-01-15 16:11 GMT+00:00 Ian Sudbery <notifications@github.com>:
